"""Create quiz_attempts table

Revision ID: 09d224024857
Revises: 21fda16e6c0f
Create Date: 2026-05-11 00:57:02.827085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d224024857'
down_revision: Union[str, Sequence[str], None] = '21fda16e6c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id_attempt', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id_quiz'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_attempt')
    )
    op.add_column('quiz_results', sa.Column('attempt_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_results', 'quiz_attempts', ['attempt_id'], ['id_attempt'])
    op.add_column('user_answers', sa.Column('attempt_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_answers', 'quiz_attempts', ['attempt_id'], ['id_attempt'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'attempt_id')
    op.drop_constraint(None, 'quiz_results', type_='foreignkey')
    op.drop_column('quiz_results', 'attempt_id')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
