"""Create enrollments table

Revision ID: 5d6ff919b206
Revises: 473a4b4418ce
Create Date: 2026-05-03 21:35:46.730661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6ff919b206'
down_revision: Union[str, Sequence[str], None] = '473a4b4418ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enrollments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_user_course', 'enrollments', ['user_id', 'course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_course', table_name='enrollments')
    op.drop_column('enrollments', 'updated_at')
    op.drop_column('enrollments', 'created_at')
    # ### end Alembic commands ###
